[package]
name = "tinysql"
version = "0.1.0"
edition = "2021"
description = "a distributed sql engine"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dev-dependencies]
tempdir = "0.3.7"

